### ISSUE TITLE
Users can crash server by sending bad data

### ISSUE THREAD

**Issue by vheuken** [bezanis/funfridge#2]
~~I did `socket.emit("send", "foo")` in the JS console and now it 503s.~~

Update: Now I can crash it with `socket.emit('send', {sessionid: sessionid, x: "A", y: "A", obj: "obj_school" })`

**Comment by vheuken** [comment]
Also w2c whatever script you're using to spell stuff so quickly?

**Comment by vheuken** [comment]
Seems to be fixed on the server. No fix on Github as far as I can tell, though.

**Comment by vheuken** [comment]
Still an issue. Now I can crash it with `socket.emit('send', {sessionid: sessionid, x: "A", y: "A", obj: "obj_school" })`

**Comment by vheuken** [comment]
I'm guessing lines 96-100 of index.js should be inside the if statement that starts on line 96?

**Comment by bezanis** [comment]
Thank you! This should be fixed now. Updated on github also.
